### ISSUE TITLE
hardcoded paths

### ISSUE THREAD

**Issue by jengelh** [CuarzoSoftware/Louvre#13]
```
src/lib/core/private/LCompositorPrivate.cpp:        if (!loadGraphicBackend("/usr/etc/Louvre/backends/libLGraphicBackendDRM.so"))
src/lib/core/private/LCompositorPrivate.cpp:            if (!loadGraphicBackend("/usr/etc/Louvre/backends/libLGraphicBackendX11.so"))
src/lib/core/private/LCompositorPrivate.cpp:        if (!loadInputBackend("/usr/etc/Louvre/backends/libLInputBackendLibinput.so"))
src/meson.build:BACKENDS_PATH = '/usr/etc/Louvre/backends'
src/meson.build:ASSETS_PATH = '/usr/etc/Louvre/assets'
```

So even if the asset path is changed in meson.build, all the programs still hard-reference /usr.

**Comment by ehopperdietzel** [comment]
Those paths are not intended to be modified, but if you need to, I will create Meson options so that they can be modified, and perhaps an environment variable to specify the default path for backends.

**Comment by 2xsaiko** [comment]
You should use the already existing options here: https://mesonbuild.com/Builtin-options.html

e.g. `get_option('datadir') / 'Louvre/assets'` and `get_option('libdir') / 'Louvre/backends'`.

**Comment by ehopperdietzel** [comment]
Fixed! 😉
