### ISSUE TITLE
Provide examples

### ISSUE THREAD

**Issue by ilovethensa** [CuarzoSoftware/Louvre#5]
My suggestion is to have an example dir with an example compositor, it could be used for quick prototyping and an example of how the library can be used

**Comment by ilovethensa** [comment]
im really dumb

**Comment by ehopperdietzel** [comment]
Hi, I guess you noticed the `/Louvre/src/examples` directory. Your suggestion is actually a great idea. I could upload a final version of what you end up with in the tutorial, which is quite basic but covers most aspects.
