### ISSUE TITLE
Wine `winewayland.drv` require `zwp_pointer_constraints_v1`

### ISSUE THREAD

**Issue by Fox2Code** [CuarzoSoftware/Louvre#50]
Reference upstream Wine: https://gitlab.winehq.org/wine/wine/-/blob/master/dlls/winewayland.drv/wayland.c?ref_type=heads#L274
Reference Valve/Proton Wine: https://github.com/ValveSoftware/wine/blob/proton_9.0/dlls/winewayland.drv/wayland.c#L272

Wayland protocol: https://wayland.app/protocols/pointer-constraints-unstable-v1
https://gitlab.freedesktop.org/wayland/wayland-protocols/-/blob/main/unstable/pointer-constraints/pointer-constraints-unstable-v1.xml

I know both Louvre and the Wine Wayland drivers are in it's early stages, I am just making this issue in advance so peoples reading on the project understand why the Wine Wayland driver currently cannot be used/tested on Louvre.
(Also as a reminder that `zwp_pointer_constraints_v1` is not yet implemented on Louvre `2.0.0` git branch)

I didn't opened a discussion instead cause it seemed out of place.

**Comment by ehopperdietzel** [comment]
Hi, thanks for pointing that out. I wasn't aware that Wine now supports Wayland, that's good to know. Regarding the pointer constraint protocol, it's scheduled to be available in Louvre 2.0.0, which is currently in development.

**Comment by ehopperdietzel** [comment]
Just FYI, I've finished adding the pointer constraints protocol to the 2.0.0 branch. It should work in all the examples now.

**Comment by Fox2Code** [comment]
@ehopperdietzel yeah, I knew when I opened the issues that you would to add it.
I'll could probs snoop around and open more issues that various protocols other toolkits might be using.
I think I'll take a look around and open issues if I find something interesting, worst case scenarios my issues could just be closed.

**Comment by ehopperdietzel** [comment]
Alright, please feel free to do so. I'm currently focused on incorporating the [wlr screencopy](https://wayland.app/protocols/wlr-screencopy-unstable-v1) protocol.

**Comment by ehopperdietzel** [comment]
The wlr-screencopy protocol is now operational (in louvre-views and louvre-weston-clone). I have recorded a [video demonstration](https://www.youtube.com/watch?v=lTBXASVZ5ug) with wf-recorder, and to my surprise, it appears really smooth (since my screen is 2880x1800px). I believe the final protocol to integrate before releasing 2.0.0 will be wlr-layer-shell.

**Comment by Fox2Code** [comment]
This is fixed in `2.0.0` I think is issue can be closed now.

@ehopperdietzel unless you want to keep this issue open for some reason, I think you should close it.
