### ISSUE TITLE
GTK doesn't support `xdg_decoration_unstable_v1` but does support `org_kde_kwin_server_decoration_manager`

### ISSUE THREAD

**Issue by Fox2Code** [CuarzoSoftware/Louvre#52]
This is very silly, GTK support KDE protocol for decoration, but not the XDG one.

Relevant code: https://gitlab.gnome.org/GNOME/gtk/-/blob/main/gdk/wayland/gdkdisplay-wayland.c
Searching for `xdg_decoration` in the entire project result in nothing
Checking for `org_kde_kwin_server_decoration_manager` gives multiple results

Relevant protocols:
- https://wayland.app/protocols/kde-server-decoration
- https://wayland.app/protocols/xdg-decoration-unstable-v1

Since Louvre already support `xdg_decoration_unstable_v1`, supporting `org_kde_kwin_server_decoration_manager` as well shouldn't be much an issue as they are almost identical protocols.

**Comment by ehopperdietzel** [comment]
It seems like it is deprecated and XDG Decoration should be preferred.

[Wayland KDE Server Decoration Protocol](https://wayland.app/protocols/kde-server-decoration)

There have been discussions about replacing it in GTK.

[GTK Merge Request](https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/6161)

So I think it's a better idea to wait for GTK to support XDG decoration.

**Comment by Fox2Code** [comment]
@ehopperdietzel It may take literal years for this GTK MR to be included, and since the KDE Decoration protocol is deprecated, it is not longer subject to change, on the other hand I don't know if there is many GTK apps that uses server side decorations, as Gnome is popularly known to be against server side decorations.

**Comment by ehopperdietzel** [comment]
I am going to consider it, but to be honest, I don't like the idea of adding two protocols for the same purpose, and even worse if one of those is deprecated. Anyway, GTK has a very robust theming system for CSD, which even allows applying border masks for round corners and such. So, in the meantime, that could be used.

**Comment by Fox2Code** [comment]
It's been 3 months and nothing productive is happening, I think the best is to ignore GTK.

LinuxMint (Peoples that make Cinnamon) started doing xapps because Gnome keep being annoying.

Maybe I'll should get a look at xapps to see if I can find something interesting there for Louvre.

**Comment by ehopperdietzel** [comment]
I'll take a look to the KDE protocol, maybe I can add it without problems.

**Comment by Fox2Code** [comment]
New GTK MR: https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/6398

**Comment by ehopperdietzel** [comment]
Nice, let's wait a few more years! 😄

**Comment by MorsMortium** [comment]
If the goal is universally disabling CSD, [GTK-NoCSD](https://codeberg.org/MorsMortium/GTK-NoCSD) can help with that. I added support for removing the internal CSD as well, for supporting River
