### ISSUE TITLE
Waybar doesn't work - Failed to register as toplevel manager

### ISSUE THREAD

**Issue by milisarge** [CuarzoSoftware/Louvre#60]
When i tried to start waybar from terminal, i am getting "Failed to register as toplevel manager" error, can it be related with, https://github.com/Alexays/Waybar/issues/1016

**Comment by Fox2Code** [comment]
Required Wayland protocol: https://wayland.app/protocols/wlr-foreign-toplevel-management-unstable-v1

**Comment by ehopperdietzel** [comment]
> When i tried to start waybar from terminal, i am getting "Failed to register as toplevel manager" error, can it be related with, https://github.com/Alexays/Waybar/issues/1016

I tested Waybar v0.10.2 and it works for me out of the box. Do you possibly have a plugin/addon that requires that protocol?

> Required Wayland protocol: https://wayland.app/protocols/wlr-foreign-toplevel-management-unstable-v1

Nice! That was off my radar and seems easy to implement. Maybe I can add it today.

**Comment by milisarge** [comment]
yes, looked again and there was a wlr related aforementioned protocol in my config, i removed that then waybar worked.

**Comment by ehopperdietzel** [comment]
Can you tell me which config was that so I can test the protocol later?

**Comment by milisarge** [comment]
[wlr/taskbar](https://github.com/Alexays/Waybar/blob/0251e25f234d24300b9f1063896e13a188fda03c/man/waybar-wlr-taskbar.5.scd?plain=1#L14)

**Comment by ehopperdietzel** [comment]
The [wlr-foreign-toplevel-management-unstable-v1](https://wayland.app/protocols/wlr-foreign-toplevel-management-unstable-v1) protocol is now supported in v2.1.0.

**Comment by milisarge** [comment]
![resim](https://github.com/CuarzoSoftware/Louvre/assets/15840648/37035d9a-90f6-4b58-8ad9-032e5a2ed41c)
confirmed with waybar
