### ISSUE TITLE
Create an IRC channel or discord

### ISSUE THREAD

**Issue by Ogromny** [CuarzoSoftware/Louvre#65]
Hi, 

Thanks for this amazing project. I think it'd be great to have a space to discuss about Louvre (creating a compositor using it, or even just contributing to it).

What do you think about creating a discord server, or an IRC channel, or even a matrix group ?

**Comment by ehopperdietzel** [comment]
Hi, thank you! I like the idea of a Discord server, I think it would be the simplest to implement, but not sure, what is a matrix group?

**Comment by ehopperdietzel** [comment]
Oops! I wasn't aware of that, and now I see what is Matrix, looks interesting, I'll check it out.

**Comment by Fox2Code** [comment]
TBH, Discord is fine, in the Linux Gaming dev everyone is collaborating fine, but I made a matrix account if there is a need to.

**Comment by ehopperdietzel** [comment]
> TBH, Discord is fine, in the Linux Gaming dev Discord server everyone is collaborating fine, but I made a matrix account if there is a need to.

I don't mind using Discord, but it's better to be inclusive. I made a [Matrix space for Louvre](https://matrix.to/#/#louvre-wayland:matrix.org), but I'm not sure if that was the right step. If anyone wants to manage it, you're very welcome to do so.

**Comment by Fox2Code** [comment]
@Ogromny and @2xsaiko you should probably join the matrix group since you both asked for it!

**Comment by ehopperdietzel** [comment]
I prefer to keep all discussions, questions, ideas, etc., here on GitHub so that everyone can see them. If someone wants to discuss something in detail or needs special assistance, we can schedule a meeting on Matrix.
