### ISSUE TITLE
Error while trying to install from yay or building manualy

### ISSUE THREAD

**Issue by Silitonix** [CuarzoSoftware/Louvre#70]
I using Arch and all packages are update
```
error: ‘srmFormatGetAlphaSubstitute’ was not declared in this scope
378 |             UInt32 alphaSubstitute = srmFormatGetAlphaSubstitute(fmt->format);
```

**Comment by ehopperdietzel** [comment]
This can be resolved by upgrading SRM to the latest version (0.7.0). I forgot to add version checks in the Louvre DRM backend. Thank you for pointing this out!

**Comment by Silitonix** [comment]
that helps me a lot thank you for helping
