### ISSUE TITLE
Louvre examples doesnt support light press clicking of trackpad

### ISSUE THREAD

**Issue by renhiyama** [CuarzoSoftware/Louvre#76]
On gnome and windows, I can just touch the trackpad to register a click, but on louvre - I need to press and get the haptic feedback on my trackpad to register a click on louvre. This would had been fine if I had an old/cheap laptop which had dedicated buttons. but since newer trackpads provide "simplicity" it makes me hard to use my trackpad to test stuff out on louvre examples 🙏

**Comment by renhiyama** [comment]
>  disables the "Disable while typing" feature.

I REALLY NEEDED THAT!
Gnome (or whatever is currently handling that) makes me hard to play games with my trackpad. I know mouse is great, but on windows I atleast can quickly do my daily quests in 10 mins :)

**Comment by ehopperdietzel** [comment]
Great! I added some code to enable "tap to click" in `louvre-views`. The changes are in the [zoom](https://github.com/CuarzoSoftware/Louvre/tree/zoom) branch if you want to try it.
