### ISSUE TITLE
Session lock support for other protocols

### ISSUE THREAD

**Issue by milisarge** [CuarzoSoftware/Louvre#77]
I tried session lock with [gtklock](https://github.com/jovanlanik/gtklock)

It needs another protocol for it, is it possible to support it in Louvre?

edit: hm according to [video](https://www.youtube.com/watch?v=k-DuNyF1XDg), it is working, which version of gtklock are you using?

![resim](https://github.com/user-attachments/assets/027106fc-dca2-470b-99bb-96d463740fa3)

**Comment by ehopperdietzel** [comment]
I am using v3.0.0, I've just tested it and still works. Your version might be outdated and using the layer shell + input-inhibitor protocols instead of [session lock](https://wayland.app/protocols/ext-session-lock-v1), which Louvre already implements.

**Comment by milisarge** [comment]
Sorry, i noticed that i have old version of gtklock, updated and it works with Louvre as expected.
