### ISSUE TITLE
Louvre-views - z-index issue

### ISSUE THREAD

**Issue by renhiyama** [CuarzoSoftware/Louvre#84]
`swww-daemon` seems to draw over everything else on screen, including all other apps. This isn't the intended case, and doesn't happen on other louvre examples (weston clone, etc). This can only be reproduced on louvre-views.
Bug found in: https://github.com/CuarzoSoftware/Louvre/blob/7f7836c322c2f76444afd9154bc9dc25962d4631/src/examples/louvre-views/src/Surface.cpp#L236

**Comment by ehopperdietzel** [comment]
It was a [silly line](https://github.com/CuarzoSoftware/Louvre/commit/e508ebd7d2ce3472b77ba59a1c91c467386bd3c2#diff-82b494f86e00023295728ad3072319e72b17f4a303e9f878f1603f43ffd812e3L14) I added to test Shelf and forgot to remove 🤦🏻‍♂️ fixed in v2.11.0-1, thanks!
